name: INDEX_BIOENTITIES_CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run tests from containers
        run: bash run-tests-in-containers.sh
